// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS2StFcUkm-mG_sEIi-s8dafvIGzASmD8',
    appId: '1:478229514958:web:142bd778b125d1d9e09e9f',
    messagingSenderId: '478229514958',
    projectId: 'lockey-2421a',
    authDomain: 'lockey-2421a.firebaseapp.com',
    databaseURL: 'https://lockey-2421a-default-rtdb.firebaseio.com',
    storageBucket: 'lockey-2421a.appspot.com',
    measurementId: 'G-BG2CF4JVN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmig08jf2UU4clB3-GPC-Y1VfLDtNZM-A',
    appId: '1:478229514958:android:ca3320d73d1e6befe09e9f',
    messagingSenderId: '478229514958',
    projectId: 'lockey-2421a',
    databaseURL: 'https://lockey-2421a-default-rtdb.firebaseio.com',
    storageBucket: 'lockey-2421a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrDLwr_07zT8SYPuJOTLyz6WzUgnqD23M',
    appId: '1:478229514958:ios:b414f7ec8e6a3fb6e09e9f',
    messagingSenderId: '478229514958',
    projectId: 'lockey-2421a',
    databaseURL: 'https://lockey-2421a-default-rtdb.firebaseio.com',
    storageBucket: 'lockey-2421a.appspot.com',
    iosClientId: '478229514958-bpl4m8ugb52o949dgvt6bi72lugoavpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrDLwr_07zT8SYPuJOTLyz6WzUgnqD23M',
    appId: '1:478229514958:ios:b414f7ec8e6a3fb6e09e9f',
    messagingSenderId: '478229514958',
    projectId: 'lockey-2421a',
    databaseURL: 'https://lockey-2421a-default-rtdb.firebaseio.com',
    storageBucket: 'lockey-2421a.appspot.com',
    iosClientId: '478229514958-bpl4m8ugb52o949dgvt6bi72lugoavpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
